name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
